const data = [
    {
      id: 1,
      video: 'wOUT5rF5zkY',
      image: '../album/moon1.jpg',
      name: 'Teri Baaton Mein Aisa Uljha Jiya',
      title:
        'Teri Baaton Mein Aisa Uljha Jiya (Hindi) 2024 | Shahid Kapoor, Kriti Sanon, Dharmendra',
      timeViews: '200k views 2 days ago',
      music: 'Teri Baaton Mein Aisa Uljha Jiya (Hindi) 2024 ',
      views: '163,523 views  1 Nov 2023',
      subscribers: '39.9K subscribers',
      user: ' Siraj moon',
      comment: '90',
      liked: '10',
      disliked: '11',
    },
  
    {
      id: 2,
      video: 'kIpuRFEGsmM',
      image: '../album/moon2.jpg',
      name: 'Lucky No Time For Love',
      title:
        'Salman Khan Latest Bollywood Blockbuster Movie | Lucky No Time For Love | Sneha Ullal Romantic Movie',
      timeViews: '3.5M views  10 years ago',
      music: 'Salman Khan Latest Bollywood Blockbuster Movie ',
      views: '3,538,184 views  30 Aug 2013',
      subscribers: '950K subscribers',
      user: ' sami mera roma',
      comment: '402',
      liked: '12k',
      disliked: '2k',
    },
    {
      id: 3,
      video: 'b1knAiEbtoE',
      image: '../album/moon3.jpg',
      name: 'Anatolian Eagles',
      title: 'Anatolian Eagles | Turkish Movie English Subtitles (Turkish Movie)',
      timeViews: '300k views 7 days ago',
      music: 'Anatolian Eagles | Turkish Movie English Subtitles (Turkish Movie)',
      views: '2.9M views  3 Nov 2012',
      subscribers: '49K subscribers',
      user: ' Simon Yeman',
      comment: '300',
      liked: '14k',
      disliked: '5k',
    },
    {
      id: 4,
      video: 'oviQ6bwkqMU',
      image: '../album/moon4.jpg',
      name: 'Blockbuster',
      title:
        'TRANSPORTER | Jason Statham Superhit Action Movie |Hollywood Blockbuster Jason Statham English Movie',
      timeViews: ' 489K views  7 years ago',
      music: 'TRANSPORTER | Jason Statham Superhit Action Movie',
      views: '489,410 views  18 Feb 2017',
      subscribers: '23.5K subscribers',
      user: ' Mino Soon',
      comment: '90',
      liked: '3K',
      disliked: '1K',
    },
  
    {
      id: 5,
      video: 'hFUuhsp532k',
      image: '../album/moon5.jpg',
      name: ' New Blockbuster',
      title:
        'Animal Movie 2024 | New Blockbuster Action Hindi Movie 2024 | New Bollywood Movies 2024',
      timeViews: '879M views  5 years ago',
      music: 'Animal Movie 2024 | New Blockbuster Action Hindi Movie 2024',
      views: '879,310,355 views  Premiered on 29 Oct 2018',
      subscribers: '12M subscribers',
      user: ' Mino Soon',
      comment: '150,878',
      liked: '8.8M',
      disliked: '5K',
    },
    {
      id: 6,
      video: 'CcYTpi9mS0Y',
      image: '../album/moon6.jpg',
      name: 'Dragon - Wu Xia',
      title:
        'Dragon - Wu Xia | Chinese Hindi Dubbed Full Action Movie | Donnie Yen, Takeshi Kaneshiro, Tang Wei ',
      timeViews: '36M views  7 years ago',
      music: 'Dragon - Wu Xia | Chinese Hindi Dubbed Full Action Movie',
      views: '36,421,278 views  19 Feb 2017',
      subscribers: '1.34M subscribers',
      user: ' tomy Root',
      comment: '13,832',
      liked: '311k',
      disliked: '2K',
    },
    {
      id: 7,
      video: 'Hqu-0Lvey08',
      image: '../album/moon7.jpg',
      name: 'Thor The Dark World',
      title:
        'Thor The Dark World New Hollywood Movie (2024) In Hindi Dubbed | Latest Hollywood Action Movie',
      timeViews: '62M views  14 years ago',
      music: 'Thor The Dark World New Hollywood Movie (2024) In Hindi Dubbed ',
      views: '62,486,827 views  14 Jul 2009',
      subscribers: '7.96M subscribers',
      user: ' someya ruma ',
      comment: '18,029 ',
      liked: '301k',
      disliked: '4K',
    },
    {
      id: 8,
      video: 'AWuxeDm1SGA',
      image: '../album/moon8.jpg',
      name: 'Hyena Road',
      title: 'Hyena Road | Full War Movie | WATCH FOR FREE',
      timeViews: '159K views  3 months ago',
      music: 'Hyena Road | Full War Movie ',
      views: '159,966 views  Premiered on 25 Jan 2024',
      subscribers: '24.4K subscribers',
      user: ' yemane asly ',
      comment: '31',
      liked: '2.1k',
      disliked: '1K',
    },
    {
      id: 9,
      video: 'dAsCncSPM4c',
      image: '../album/moon9.jpg',
      name: 'NOAH - The Great Biblical Flood',
      title:
        'NOAH - The Great Biblical Flood | HD Quality | Russel Crowe | Emma Watson | Hindi Dubbed Version|',
      timeViews: '1.8M views  7 months ago',
      music: 'NOAH - The Great Biblical Flood | HD Quality ',
      views: '1,821,763 views  26 Sept 2023',
      subscribers: '19.3K subscribers',
      user: 'Root Room ',
      comment: '31',
      liked: '9.5k',
      disliked: '2K',
    },
  
    {
      id: 10,
      video: 'H1XxUZAOT34',
      image: '../album/moon10.jpg',
      name: 'Blood and Bone',
      title: ' Blood and Bone (2009) full movie with subtitles',
      timeViews: '1.8M views  7 months ago',
      music: 'Blood and Bone (2009) full movie with subtitles ',
      views: '1,821,763 views  26 Sept 2023',
      subscribers: '19.3K subscribers',
      user: 'Root Room ',
      comment: '31',
      liked: '9.5k',
      disliked: '2K',
    },
    {
      id: 11,
      video: 'H-VjFCQ1JjY',
      image: '../album/moon11.jpg',
      name: 'THE SOLDIER',
      title:
        'THE SOLDIER - Hollywood Blockbuster Action Full Movie In English | Dave Bautista Latest Action Movie',
      timeViews: '1.8M views  7 months ago',
      music: 'THE SOLDIER - Hollywood Blockbuster Action Full Movie In English',
      views: '1,821,763 views  26 Sept 2023',
      subscribers: '19.3K subscribers',
      user: 'Root Room ',
      comment: '31',
      liked: '9.5k',
      disliked: '2K',
    },
    {
      id: 12,
      video: '-TqdvvfU234',
      image: '../album/moon12.jpg',
      name: 'Vedaa',
      title:
        'Vedaa | John Abraham & Sharvari Wagh | Latest Bollywood Full Action Hindi Dubbed Cinema 2024',
      timeViews: '1.8M views  7 months ago',
      music: 'Vedaa | John Abraham & Sharvari Wagh',
      views: '1,821,763 views  26 Sept 2023',
      subscribers: '19.3K subscribers',
      user: 'Root Room ',
      comment: '31',
      liked: '9.5k',
      disliked: '2K',
    },
  ]
  
  export default data
  